name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - run: echo Hello step 1
      shell: bash
    - run: echo Hello step 2
      if: ${{ always() }}
      shell: bash
    - run: echo hello step 3
      shell: bash
