name: 'Hello World'
description: 'Greet someone'
inputs:
  number:  
    description: 'number'
    required: false
    default: 1
  bool:  
    description: 'bool'
    required: false
    default: false
  string:  
    description: 'string'
    required: false
    default: 'default'
runs:
  using: "composite"
  steps:
    - run: |
        echo ${{ inputs.number }}
        echo ${{ inputs.bool }}
        echo ${{ inputs.string }}
        set -x
        [ '${{ inputs.number == 1 }}' = true ]
        #[ '${{ inputs.number == '1' }}' = true ]
        [ '${{ inputs.bool == 'true' }}' = true ]
        [ '${{ inputs.bool == true }}' = true ]
      shell: bash
 