apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "application.fullname" . }} 
  template:
    metadata: 
      labels:
        app: {{ include "application.fullname" . }}
      annotations:
        timestamp: {{ now | quote }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: {{ include "application.fullname" . }}
        ports:
        - name: http
          containerPort: {{ .Values.application.ports.http }}
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: {{ .Values.application.configuration.environment }}
          {{- range .Values.appEnv }}
        - name: {{ .name | quote }}
          value: {{ .value | quote }}
          {{- end }}
      imagePullSecrets:
        - name: {{ .Values.docker.secretName }}