{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullname" . }}-ingress
  annotations:
    timestamp: {{ now | quote }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "application.fullname" . }}
            port:
              number: {{ .Values.service.port }}

{{- end }}
