apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "application.fullname" . }}
  name: {{ include "application.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.ports.http }}
  selector:
    app: {{ include "application.fullname" . }}
 