apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "application.fullname" . }}-external
  name: {{ include "application.fullname" . }}-external
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.ports.http }}
  selector:
    app: {{ include "application.fullname" . }}
