image:
  repository: dd/dd
  tag: "latest"
replicaCount: 2
application:
  ports:
    http: 80
  configuration:
    environment: "Development"
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false
