on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:  
    - id: foo
      run: |
        sleep 100000
  example1:
    runs-on: ubuntu-latest
    needs:
      - example
    if: ${{ always() }}
    steps:  
    - name: First1222
      if: true
      run: |
        echo first
  example2:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:  
    - name: First1222
      if: true
      run: |
        echo first
  
