on:
  push:
    branches:
      - main
    tags:
      - v2
jobs:
  types:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: test
        uses: alexeysas/test-deployment-app@main
        with:
          number: 1
          bool: true
          string: "1"
  types2:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: test2
        uses: alexeysas/test-deployment-app@main
        with:
          number: "1"
          bool: "true"
          string: "1"
