on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Check string truthiness with OR operator both
      run: echo "At least one string is truthy"
      if: ${{ false || 'ddd' }}
    - name: Check string truthiness with OR operator one empty
      run: echo "At least one string is truthy"
      if: ${{ false || '' }}
    - name: Check string truthiness with OR operator one boolean false
      run: echo "At least one string is truthy"
      if: ${{ false || '' }}
    - name: Check string truthiness with OR operator one false
      run: echo "At least one string is truthy"
      if: ${{ false || 'false' }}
    - name: Check string truthiness with OR operator one 0
      run: echo "At least one string is truthy"
      if: ${{ false || '0' }}
    - name: Check string truthiness with OR operator one 00
      run: echo "At least one string is truthy"
      if: ${{ false || '00' }}
    - name: Check string truthiness with OR operator one 1
      run: echo "At least one string is truthy"
      if: ${{ false || '1' }}
    - name: Check string truthiness with OR operator false
      run: echo "At least one string is truthy"
      if: ${{ false || false }}
    - name: Check string truthiness with OR operator false 2
      run: echo "At least one string is truthy"
      if: false
