on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Log level'
        required: true
        default: true
        type: boolean
      testStr:
        description: 'Log level'
        required: true
        default: true
        type: string
jobs:
   test:
      runs-on: ubuntu-latest
      steps:
        - run: |        
            echo "${{ inputs.test == true }}"
            echo "${{ inputs.test == 'true' }}"
            echo "${{ inputs.testStr == true }}"
            echo "${{ inputs.testStr == 'true' }}"
          if: inputs.test
