on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Log level'
        required: true
        default: true
        type: boolean
      testStr:
        description: 'Log level'
        required: true
        default: true
        type: string
      testBoolStr:
        description: 'Log level'
        required: true
        default: 'true'
        type: boolean
      testStrStr:
        description: 'Log level'
        required: true
        default: 'true'
        type: string
jobs:
   test:
      runs-on: ubuntu-latest
      steps:
        - run: |        
            echo "${{ inputs.test == true }}"       # true
            echo "${{ inputs.test == 'true' }}"     # false
            echo "${{ inputs.testStr == true }}"    # false
            echo "${{ inputs.testStr == 'true' }}"  # true

            echo "${{ inputs.testBoolStr == true }}"    # true
            echo "${{ inputs.testBoolStr == 'true' }}"  # false

            echo "${{ inputs.testStrStr == true }}"     # false 
            echo "${{ inputs.testStrStr == 'true' }}"   # true

            echo  "${{ inputs.testBoolStr == inputs.test }}" 
          if: inputs.test
