on: [push]

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yaml
    with:
      config-path: .github/labeler.yml
    secrets: inherit
  job1:
    needs: [call-workflow-passing-data]
    runs-on: ubuntu-latest
    name: job1
    steps:
      - run: echo "job1 step1 outside"
        shell: bash
      - run: echo "job1 step2 outside"
        shell: bash  
  job3r:
    needs: [call-workflow-passing-data, job1]
    uses: ./.github/workflows/reusable.yaml
    with:
      config-path: .github/labeler.yml
    secrets: inherit
