on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: alexeysas/test-deployment-app/github/action@develop
      - run: echo normal
        shell: bash