on: [push]

jobs:
  job1r:
    uses: ./.github/workflows/reusable.yaml
    with:
      config-path: .github/labeler.yml
    secrets: inherit
  job2:
    needs: [job1r]
    runs-on: ubuntu-latest
    name: job1
    steps:
      - run: echo "job1 step1 outside"
        shell: bash
      - run: echo "job1 step2 outside"
        shell: bash  
  job3r:
    needs: [job1r, job2]
    uses: ./.github/workflows/reusable.yaml
    with:
      config-path: .github/labeler.yml
    secrets: inherit
