
on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:  
    - id: foo
      uses: alexeysas/test-deployment-app@v1
      with:
        who-to-greet: 'Mona the Octocat'
    - name: First1222
      continue-on-error: true
      run: |
        bad 
    - name: First12223
      if: true
      run: |
        echo dsds
